import { createSlice } from "@reduxjs/toolkit";

const things = createSlice({
    name: "things",
    initialState: {
        things: [
            {
                id: 'w-1',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/womens/1.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'w-2',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/womens/2.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'w-3',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/womens/3.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'w-4',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/womens/4.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'w-5',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/womens/5.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'w-6',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/womens/6.png`],
                descr:"",
                price: 30,
                discount: 50,
                rating: 4,
            },
            {
                id: 'w-7',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/womens/7.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'w-8',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/womens/8.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'm-1',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/mens/1.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'm-2',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/mens/2.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'm-3',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/mens/3.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'm-4',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/mens/4.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'm-5',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/mens/5.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'm-6',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/mens/6.png`],
                descr:"",
                price: 30,
                discount: 50,
                rating: 4,
            },
            {
                id: 'm-7',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/mens/7.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
            {
                id: 'm-8',
                sizes: [],
                name:"Women's tracksuit Q109",
                img: [`${process.env.PUBLIC_URL}/imgs/cards/mens/8.png`],
                descr:"",
                price: 30,
                discount: 0,
                rating: 4,
            },
        ],
    },
});

export default (things.reducer);